services:
  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /usr/app/node_modules
      - ./backend/nodemon.json:/app/nodemon.json
    environment:
      - BDD_ENDPOINT=${BDD_ENDPOINT:-postgresql://root:Sklort@123@localhost:5432/hackathon}
      - SERVER_PORT=${SERVER_PORT:-3010}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8082:${SERVER_PORT:-3010}"
  db:
    image: postgres
    container_name: dbb
    restart: always
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Sklort@123
      POSTGRES_DB: hackathon
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    container_name: frontendd
    build:
      context: ./frontend
      target: dev
      args:
        - VITE_URL_PREFIX=${VITE_URL_PREFIX}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3020:82"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
